"""Increase content length

Revision ID: eb728adb2a5c
Revises: 59ed098d126e
Create Date: 2025-10-01 12:30:30.243375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb728adb2a5c'
down_revision: Union[str, Sequence[str], None] = '59ed098d126e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
                    existing_type=mysql.VARCHAR(length=100),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('posts', 'content',
                    existing_type=mysql.VARCHAR(length=100),
                    type_=sa.String(length=2000),
                    existing_nullable=False)
    op.alter_column('posts', 'summary',
                    existing_type=sa.VARCHAR(length=300),
                    type_=sa.String(length=500),
                    existing_nullable=True)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.alter_column('posts', 'content',
                    existing_type=sa.String(length=2000),
                    type_=mysql.VARCHAR(length=100),
                    existing_nullable=False)
    op.alter_column('posts', 'title',
                    existing_type=sa.String(length=255),
                    type_=mysql.VARCHAR(length=100),
                    existing_nullable=False)
    # ### end Alembic commands ###
